#ifndef DEFS_H 
#define DEFS_H

#define PUBLISH_ODOM_PATH
#define PUBLISH_ISAM_PATH

#define DISABLE_SMOOTHNET3D
// #define DISABLE_KEY_FRAMES
// #define DISABLE_LOOP_CLOSURE
#define LOOP_CLOSURE_RATE 50
// #define DISABLE_MAP_FIXES

#endif
